
version: 2.1

jobs:
  build-deploy-dev:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker-compose -f src/docker-compose.dev.yaml up -d --build 

      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            docker tag $IMAGE_NAME registry.heroku.com/$APP_NAME/web
            docker push registry.heroku.com/$APP_NAME/web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a $APP_NAME web

workflows:
  build-deploy-dev:
    jobs:
      - build-deploy-dev:
          filters:
            branches:
              only:
                - main