version: '3.7'

services:

    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - './client/:/app'
            - '/app/node_modules'
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - 80:80
        depends_on:
            - client  
    

    