version: '3.2'

services: 
    api:
        image: wanyaland/victoria_university:api

        volumes:
            - ./app/:/usr/src/app
        ports:
            - 8009:8009
        env_file:
            - ./app/.env
        depends_on: 
            - db
    
    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=vu_user
            - POSTGRES_PASSWORD=Pas55word!
            - POSTGRES_DB=vu_prod

    client:
        image: wanyaland/victoria_university:web
        volumes:
            - './client/:/usr/src/app'
            - '/usr/src/app/node_modules'
        ports:
            - 3001:3000

    nginx:
        image: wanyaland/victoria_university:nginx
        restart: always
        ports:
          - 80:80
        depends_on:
          - api
          - client
        
volumes:
    postgres_data: