version: '3.2'

services: 
    api:
        image: wanyaland/victoria_university:api
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8009:8009
        depends_on: 
            - db
    
    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=vu_user
            - POSTGRES_PASSWORD=Pas55word!
            - POSTGRES_DB=vu_prod

    client:
        image: wanyaland/victoria_university:web
        command: npm start
        volumes:
            - client:/usr/src/app/client
            - node:/usr/src/app/client/node_modules
        environment:
            - NODE_ENV=production
        ports:
            - 3001:3000

    nginx:
        image: wanyaland/victoria_university:nginx
        restart: always
        ports:
          - 80:80
        depends_on:
          - api
          - client
        
volumes:
    postgres_data:
    client:
    node: