version: '3.2'

services:

    client:
        image: wanyaland/victoria_university:web
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - './client/:/app'
            - '/app/node_modules'
        ports:
            - 3000:3000
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - 80:80
        depends_on:
            - client  
    

    