version: '3.2'

services: 
    core:
        image: wanyaland/victoria_university:api
        build: ./app
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./app/:/usr/src/app
        ports:
            - 8000:8000
        env_file:
            - ./app/.env.dev
        depends_on: 
            - db
    
    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=vu_user
            - POSTGRES_PASSWORD=Pas55word!
            - POSTGRES_DB=vu_dev
    
    db-test:
        image: postgres:12-alpine
        volumes:
            - postgres_test_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=vu_user
            - POSTGRES_PASSWORD=Pas55word!
            - POSTGRES_DB=vu_dev

    client:
        image: wanyaland/victoria_university:web
        container_name: client
        build: 
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - './client/:/usr/src/app/client'
            - '/usr/src/app/client/node_modules'
        ports:
            - 3001:3000
        environment: 
            - NODE_ENV=development
        depends_on: 
            - core
        
volumes:
    postgres_data:
    postgres_test_data:
    

    