version: '3.2'

services: 
    api:
        image: wanyaland/vu_api
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8009:8009
        depends_on: 
            - db
        env_file:
            - ./.env
    
    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=vu_user
            - POSTGRES_PASSWORD=Pas55word!
            - POSTGRES_DB=vu_prod

    client:
        image: wanyaland/vu_web
        command: npm start
        volumes:
            - client:/usr/src/app/client
            - node:/usr/src/app/client/node_modules
        environment:
            - NODE_ENV=production
        env_file:
            - ./.env
        ports:
            - 3001:3000

    nginx:
        image: wanyaland/vu_nginx
        restart: always
        ports:
            - 443:443
            - 80:80
        depends_on:
          - api
          - client
        env_file:
            - ./.env
        volumes:
            - ./nginx/certbot/conf:/etc/letsencrypt
            - ./nginx/certbot/www:/var/www/certbot
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./nginx/certbot/conf:/etc/letsencrypt
            - ./nginx/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        
volumes:
    postgres_data:
    client:
    node: